// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/task.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataType int32

const (
	DataType_string DataType = 0
	DataType_int    DataType = 1
	DataType_double DataType = 2
	DataType_long   DataType = 3
)

var DataType_name = map[int32]string{
	0: "string",
	1: "int",
	2: "double",
	3: "long",
}

var DataType_value = map[string]int32{
	"string": 0,
	"int":    1,
	"double": 2,
	"long":   3,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34c75787857fc9ed, []int{0}
}

type IPartition struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Tasks                []*Task  `protobuf:"bytes,2,rep,name=Tasks,proto3" json:"Tasks,omitempty"`
	Rows                 []*Row   `protobuf:"bytes,3,rep,name=Rows,proto3" json:"Rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPartition) Reset()         { *m = IPartition{} }
func (m *IPartition) String() string { return proto.CompactTextString(m) }
func (*IPartition) ProtoMessage()    {}
func (*IPartition) Descriptor() ([]byte, []int) {
	return fileDescriptor_34c75787857fc9ed, []int{0}
}

func (m *IPartition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPartition.Unmarshal(m, b)
}
func (m *IPartition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPartition.Marshal(b, m, deterministic)
}
func (m *IPartition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPartition.Merge(m, src)
}
func (m *IPartition) XXX_Size() int {
	return xxx_messageInfo_IPartition.Size(m)
}
func (m *IPartition) XXX_DiscardUnknown() {
	xxx_messageInfo_IPartition.DiscardUnknown(m)
}

var xxx_messageInfo_IPartition proto.InternalMessageInfo

func (m *IPartition) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *IPartition) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *IPartition) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Row struct {
	CompressRow          []byte   `protobuf:"bytes,2,opt,name=compressRow,proto3" json:"compressRow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_34c75787857fc9ed, []int{1}
}

func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetCompressRow() []byte {
	if m != nil {
		return m.CompressRow
	}
	return nil
}

type Task struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Plugin               string               `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Instruction          []string             `protobuf:"bytes,3,rep,name=instruction,proto3" json:"instruction,omitempty"`
	InstructionParams    []*any.Any           `protobuf:"bytes,4,rep,name=instructionParams,proto3" json:"instructionParams,omitempty"`
	CreationTime         *timestamp.Timestamp `protobuf:"bytes,5,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_34c75787857fc9ed, []int{2}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Task) GetPlugin() string {
	if m != nil {
		return m.Plugin
	}
	return ""
}

func (m *Task) GetInstruction() []string {
	if m != nil {
		return m.Instruction
	}
	return nil
}

func (m *Task) GetInstructionParams() []*any.Any {
	if m != nil {
		return m.InstructionParams
	}
	return nil
}

func (m *Task) GetCreationTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreationTime
	}
	return nil
}

type IPartitionResult struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TaskResults          []*TaskResult        `protobuf:"bytes,2,rep,name=taskResults,proto3" json:"taskResults,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *IPartitionResult) Reset()         { *m = IPartitionResult{} }
func (m *IPartitionResult) String() string { return proto.CompactTextString(m) }
func (*IPartitionResult) ProtoMessage()    {}
func (*IPartitionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_34c75787857fc9ed, []int{3}
}

func (m *IPartitionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPartitionResult.Unmarshal(m, b)
}
func (m *IPartitionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPartitionResult.Marshal(b, m, deterministic)
}
func (m *IPartitionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPartitionResult.Merge(m, src)
}
func (m *IPartitionResult) XXX_Size() int {
	return xxx_messageInfo_IPartitionResult.Size(m)
}
func (m *IPartitionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_IPartitionResult.DiscardUnknown(m)
}

var xxx_messageInfo_IPartitionResult proto.InternalMessageInfo

func (m *IPartitionResult) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *IPartitionResult) GetTaskResults() []*TaskResult {
	if m != nil {
		return m.TaskResults
	}
	return nil
}

func (m *IPartitionResult) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type TaskResult struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Status               bool                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Rows                 []*Row               `protobuf:"bytes,3,rep,name=Rows,proto3" json:"Rows,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TaskResult) Reset()         { *m = TaskResult{} }
func (m *TaskResult) String() string { return proto.CompactTextString(m) }
func (*TaskResult) ProtoMessage()    {}
func (*TaskResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_34c75787857fc9ed, []int{4}
}

func (m *TaskResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResult.Unmarshal(m, b)
}
func (m *TaskResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResult.Marshal(b, m, deterministic)
}
func (m *TaskResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResult.Merge(m, src)
}
func (m *TaskResult) XXX_Size() int {
	return xxx_messageInfo_TaskResult.Size(m)
}
func (m *TaskResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResult.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResult proto.InternalMessageInfo

func (m *TaskResult) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *TaskResult) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *TaskResult) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *TaskResult) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func init() {
	proto.RegisterEnum("protos.DataType", DataType_name, DataType_value)
	proto.RegisterType((*IPartition)(nil), "protos.IPartition")
	proto.RegisterType((*Row)(nil), "protos.Row")
	proto.RegisterType((*Task)(nil), "protos.Task")
	proto.RegisterType((*IPartitionResult)(nil), "protos.IPartitionResult")
	proto.RegisterType((*TaskResult)(nil), "protos.TaskResult")
}

func init() { proto.RegisterFile("protos/task.proto", fileDescriptor_34c75787857fc9ed) }

var fileDescriptor_34c75787857fc9ed = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x8a, 0xdb, 0x30,
	0x10, 0x86, 0xab, 0xd8, 0xbb, 0x89, 0xc7, 0x39, 0x78, 0x45, 0x29, 0x6e, 0x2e, 0x6b, 0x7c, 0xa9,
	0xe9, 0xc1, 0x81, 0xed, 0xf6, 0x5a, 0xe8, 0xd2, 0x4b, 0x6f, 0x8b, 0xf0, 0xa9, 0x37, 0x25, 0x51,
	0x8d, 0x58, 0x5b, 0x32, 0x96, 0x84, 0xc9, 0x53, 0x14, 0xfa, 0x74, 0x7d, 0x9c, 0x22, 0x29, 0x26,
	0x4e, 0x93, 0x92, 0xbd, 0x69, 0xfe, 0xf9, 0x66, 0xf2, 0xeb, 0x57, 0x0c, 0x77, 0x5d, 0x2f, 0xb5,
	0x54, 0x6b, 0x4d, 0xd5, 0x4b, 0xe9, 0xce, 0xf8, 0xd6, 0x4b, 0xab, 0xfb, 0x5a, 0xca, 0xba, 0x61,
	0x6b, 0x57, 0x6e, 0xcc, 0xcf, 0xb5, 0xe6, 0x2d, 0x53, 0x9a, 0xb6, 0x9d, 0x07, 0x57, 0xef, 0xff,
	0x05, 0xa8, 0xd8, 0xfb, 0x56, 0xce, 0x00, 0xbe, 0x3f, 0xd3, 0x5e, 0x73, 0xcd, 0xa5, 0xc0, 0x18,
	0x42, 0x63, 0xf8, 0x2e, 0x45, 0x19, 0x2a, 0x22, 0xe2, 0xce, 0x38, 0x87, 0x9b, 0x8a, 0xaa, 0x17,
	0x95, 0xce, 0xb2, 0xa0, 0x88, 0x1f, 0x96, 0x7e, 0x50, 0x95, 0x56, 0x24, 0xbe, 0x85, 0xef, 0x21,
	0x24, 0x72, 0x50, 0x69, 0xe0, 0x90, 0x78, 0x44, 0x88, 0x1c, 0x88, 0x6b, 0xe4, 0x1f, 0x20, 0x20,
	0x72, 0xc0, 0x19, 0xc4, 0x5b, 0xd9, 0x76, 0x3d, 0x53, 0x8a, 0xc8, 0x21, 0x9d, 0x65, 0xa8, 0x58,
	0x92, 0xa9, 0x94, 0xff, 0x41, 0x10, 0xda, 0x9d, 0x17, 0xad, 0xbc, 0x83, 0xdb, 0xae, 0x31, 0x35,
	0x17, 0x6e, 0x32, 0x22, 0x87, 0xca, 0xae, 0xe5, 0x42, 0xe9, 0xde, 0x6c, 0xed, 0x2d, 0x9c, 0x8b,
	0x88, 0x4c, 0x25, 0xfc, 0x04, 0x77, 0x93, 0xf2, 0x99, 0xf6, 0xb4, 0x55, 0x69, 0xe8, 0xdc, 0xbe,
	0x2d, 0x7d, 0x3a, 0xe5, 0x98, 0x4e, 0xf9, 0x55, 0xec, 0xc9, 0x39, 0x8e, 0xbf, 0xc0, 0x72, 0xdb,
	0x33, 0x6a, 0x95, 0x8a, 0xb7, 0x2c, 0xbd, 0xc9, 0x50, 0x11, 0x3f, 0xac, 0xce, 0xc6, 0xab, 0x31,
	0x7d, 0x72, 0xc2, 0xe7, 0xbf, 0x11, 0x24, 0xc7, 0xac, 0x09, 0x53, 0xa6, 0xd1, 0x17, 0xaf, 0xf9,
	0x08, 0xb1, 0x7d, 0x65, 0x4f, 0x8c, 0xb9, 0xe3, 0x93, 0xdc, 0x5d, 0x8b, 0x4c, 0x31, 0xfc, 0x08,
	0x73, 0x26, 0x76, 0xce, 0x59, 0x70, 0xd5, 0xd9, 0x88, 0xe6, 0xbf, 0x10, 0xc0, 0x71, 0xe3, 0xff,
	0x52, 0x57, 0x9a, 0x6a, 0xa3, 0x5c, 0xea, 0x0b, 0x72, 0xa8, 0xae, 0x3e, 0xfa, 0xd4, 0x51, 0xf8,
	0x6a, 0x47, 0x1f, 0x3f, 0xc3, 0xe2, 0x1b, 0xd5, 0xb4, 0xda, 0x77, 0x0c, 0x83, 0xfd, 0xe9, 0x9e,
	0x8b, 0x3a, 0x79, 0x83, 0xe7, 0x10, 0x70, 0xa1, 0x13, 0x64, 0xc5, 0x9d, 0x34, 0x9b, 0x86, 0x25,
	0x33, 0xbc, 0x80, 0xb0, 0x91, 0xa2, 0x4e, 0x82, 0xa7, 0xe8, 0xc7, 0xdc, 0xff, 0xbf, 0xd5, 0xc6,
	0x7f, 0x17, 0x9f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x3c, 0x61, 0x23, 0x33, 0x03, 0x00,
	0x00,
}
